services:
  server:
    build: ./server
    container_name: server
    image: igelschnauzen/blok-server
    ports: 
      - 3000:3000
    networks:
      - blok-network
    depends_on:
      - db

  socket:
    build: ./socket
    image: igelschnauzen/blok-socket
    container_name: socket
    ports:
      - 5000:5000
    networks:
      - blok-network
  
  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - blok-network
    

  client:
    build: ./client
    image: igelschnauzen/blok-client
    container_name: client
    ports:
      - 8000:8000
    networks:
      - blok-network

  nginx:
    build: ./nginx
    image: igelschnauzen/blok-nginx
    container_name: nginx
    ports: 
      - 80:80
    networks:
      - blok-network
    depends_on:
      - server
      - client
      - socket
      - db

volumes:
  db-data:
    name: db-data

networks:
  blok-network:
    driver: bridge
